server.port=8080

spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/transperent_ksk_db
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=7842dh6ju3e324yd23has8dh7as87dh7q8hd9qi8182d8453swu2873js32uh273hsq2t762
jwt.lifetime=30m
server.servlet.context-path=/api

